language: python
sudo: false

cache:
  directories: cache

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.5"

before_install:
  - pip install pyflakes
  - pip install pep8

before_script:
  - pyflakes .
  - pep8 . --max-line-length 99 --ignore E302

script:
  - python hererocks.py here -l 5.3 -r^ --downloads cache --builds cache
  - export PATH=$PATH:$PWD/here/bin
  - lua -v
  - luarocks --version
  - luarocks make
  - hererocks-test
  - rm here -r
  - python hererocks.py here -j 2.1 -r^ --downloads cache --builds cache
  - lua -v
  - luarocks --version
  - luarocks make
  - hererocks-test
