language: python
sudo: false

os:
  - linux
  - osx

cache:
  directories: test/cache

python:
  - "2.7"
  - "3.2"
  - "3.5"

install:
  - pip install pyflakes
  - pip install pep8

script:
  - pyflakes .
  - pep8 .
  - ./test.sh
