version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: 5.1
  - LUA: 5.2
  - LUA: 5.3

configuration: MinGW

platform: x86

install: cinst python

before_build: set PATH=C:\mingw\bin;%PATH%

build_script: python hererocks.py here --lua "%LUA%" --verbose

test_script: here\bin\lua -v
