version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: 5.1
  - LUA: 5.2
  - LUA: 5.3

configuration: MinGW

platform: x86

install: cinst python

build_script: python hererocks.py here --lua "%LUA%" --luarocks 2.1.2 --verbose

test_script:
  - here\bin\lua -v
  - here\bin\luarocks --version
