version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: 5.1
  - LUA: 5.2
  - LUA: 5.3

configuration:
- 2015

platform: x86

before_build: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"'

build_script: python hererocks.py here --lua "%LUA%" --verbose --target cl

test_script: here\bin\lua -v
